### ISSUE TITLE
Ruby 2.6.4 support

### ISSUE THREAD

**Issue by elalemanyo** [eregon/ruby-install-builder#1]
Hi,
Would be great if you can add 2.6.4 version support.

Thanks in advance

**Comment by eregon** [comment]
Hello, thank you for opening an issue.

Ruby 2.6.4 is known to have a string corruption bug:
https://bugs.ruby-lang.org/issues/16136

To understand better, is there a particular reason you want to test against Ruby 2.6.4 and not Ruby 2.6.5 (which fixes that bug)?

**Comment by elalemanyo** [comment]
The reason was that my app was running using 2.6.4, but I would just update it.
Thanks for telling me about the issue.
After the update is done I would test `use-ruby-action` :-)

Thanks

**Comment by eregon** [comment]
Thanks for the reply.
I'm not sure yet on which versions we should add here yet.

But indeed when it's easily possible to use the latest release of the same 2.minor "branch" then it seems best to do so as that includes more bug fixes and therefore makes it less likely to hit known bugs.

**Comment by eregon** [comment]
Ruby 2.6.4 is now available, if you want to use it:
https://github.com/eregon/use-ruby-action/#supported-versions
I would still advise to update to Ruby 2.6.5 to avoid that String corruption bug.
